# Documentation: http://docs.travis-ci.com/user/languages/julia/
dist: trusty
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.3
  - nightly
matrix:
  fast_finish: true
before_script:
  - curl -OL http://gmsh.info/bin/Linux/gmsh-4.4.1-Linux64-sdk.tgz
  - tar xfv gmsh-4.4.1-Linux64-sdk.tgz
  - GMSHROOT=`pwd`/gmsh-4.4.1-Linux64-sdk
  - export PATH=$PATH:$GMSHROOT/bin
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email:
    on_success: never
    on_failure: always
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
