name = "GridapGmsh"
uuid = "3025c34a-b394-11e9-2a55-3fee550c04c8"
authors = ["Francesc Verdugo <fverdugo@cimne.upc.edu>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
